### PR TITLE
Add Azure Blob Storage adapter

### PR DESCRIPTION
**Pull request by developernurullah**
Hello There,

Kindly merge branch for Azure Blob Support

### CODE REVIEW

**Comment by bytehead** [comment]
Thank you!
Sadly the tests still fail.

Can you have a look and fix the code style accordingly and add the `league/flysystem-azure-blob-storage:^3.0
` to the `require-dev` section of the `composer.json`?

**Comment by bytehead** [comment]
Seems it's PHP 8+ only. So I'll drop PHP 7 support as 7.4 is EOL anyway.

**Comment by navneetbhardwaj** [comment]
@bytehead 
thanks, What ETA to drop the support of PHP 7?

**Review by bytehead — APPROVED** [review]

**Comment by bytehead** [comment]
[4.5.0](https://github.com/1up-lab/OneupFlysystemBundle/releases/tag/4.5.0) is released 🥳

**Comment by navneetbhardwaj** [comment]
@bytehead  thank you very much.

**Comment by developernurullah** [comment]
@bytehead Thank you very much

**Pull request merged**
