### PR TITLE
Remove copy adapter

### PR DESCRIPTION
**Pull request by akeeman**
The service doesn't seem to exist anymore.

### CODE REVIEW

**Comment by bytehead** [comment]
See https://github.com/thephpleague/flysystem-copy/issues/16 for confirmation.

**Comment by bytehead** [comment]
Can't remove this in a minor release, but I'll add some deprecation notices. To be removed in `2.0.0`.

**Comment by bytehead** [comment]
They actually deleted their repo as well.
We have to remove `league/flysystem-copy` from `oneup/flysystem-bundle` because it's not installable anymore:
```
    Failed to download barracuda/copy from source: Failed to clone https://github.com/copy-app/php-client-library.git via https, ssh protocols, aborting.
- https://github.com/copy-app/php-client-library.git
  Cloning into '/home/travis/build/1up-lab/OneupFlysystemBundle/vendor/barracuda/copy'...
  remote: Invalid username or password.
  fatal: Authentication failed for 'https://github.com/copy-app/php-client-library.git/'
- git@github.com:copy-app/php-client-library.git
  Cloning into '/home/travis/build/1up-lab/OneupFlysystemBundle/vendor/barracuda/copy'...
  Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
  Permission denied (publickey).
  fatal: Could not read from remote repository.
  
  Please make sure you have the correct access rights
  and the repository exists.
    Now trying to download from dist
  - Installing barracuda/copy (1.1.7) Downloading: Failed
Installation failed, reverting ./composer.json to its original content.
                                                                               
  [Composer\Downloader\TransportException]                                     
  The "https://api.github.com/repos/copy-app/php-client-library/zipball/83d8b  
  7e93b3cdc6c6a978f1d88d26b31eac4a255" file could not be downloaded (HTTP/1.1  
   404 Not Found)                                                              
```

So that breaks BC anyway. What do you think about it @akeeman?

**Comment by akeeman** [comment]
They did indeed. 

BC has been broken by dependencies, so only people that have made some in-place replacement (e.g. a fork) for the underlying barracuda/copy package will notice the removal. However, it's not an option to not-remove the dependency from composer.json. So the options are:

a) remove everything in a minor version release, potentially leaving a few broken projects behind (they can limit their version to a working one).
b) remove only the dependencies in a minor version release, and finish it up in a major. People with broken projects should add the dependency to their own project if they didn't already.

So you cannot go further without being sure to not break anything, but have choices in damage control.
As people providing a modified version of barracuda/copy themselves should have seen this change coming, I'd say go for the minor release. It's okay to break their project.

**Comment by bytehead** [comment]
Thank you for the feedback.
I'm fine with version a), I have to remove the dependency anyway because of the CI.

> (they can limit their version to a working one).

The whole service of copy.com is down, so even a working one probably won't run properly 🙈

**Comment by bytehead** [comment]
Thank you for the PR 👍

**Pull request merged**
