### PR TITLE
Add support for Symfony 3

### PR DESCRIPTION
**Pull request by rdrenth**
Add support for Symfony 3

### CODE REVIEW

**Comment by JHGitty** [comment]
ping @bytehead

**Comment by bytehead** [comment]
I've pushed a new branch [feature/symfony3](https://github.com/1up-lab/OneupFlysystemBundle/tree/feature/symfony3). Could you test that within a Symfon3 installation?

**Comment by rdrenth** [comment]
Tested the branch feature/symfony3 on Symfony 2.7, 2.8 and 3.0 (symfony-standard edition), and it works fine!

**Comment by bytehead** [comment]
Thanks for contributing and testing! Here's the new release: [1.2.0](https://github.com/1up-lab/OneupFlysystemBundle/releases/tag/1.2.0).

**Comment by rdrenth** [comment]
No problem, and thanks!

**Pull request merged**
