### PR TITLE
Dropbox API v2

### PR DESCRIPTION
**Pull request by simoheinonen**
fixes https://github.com/1up-lab/OneupFlysystemBundle/issues/142

Dropbox API v1 has been deprecated and will be shutting down June 28th 2017. Package `league/flysystem-dropbox` has been deprecated as well and suggests now using `spatie/flysystem-dropbox`

### CODE REVIEW

**Comment by simoheinonen** [comment]
Should still test it in real life

**Comment by simoheinonen** [comment]
Well... Uh.. How do you feel about dropping PHP5 support?

**Comment by bytehead** [comment]
Thanks for the PR!
Dropping PHP5 probably needs a new major version (`2.0`)...

**Comment by simoheinonen** [comment]
`spatie/flysystem-dropbox` requires `spatie/dropbox-api` and both of them require PHP 7 😞

**Comment by simoheinonen** [comment]
This PR breaks BC anyway though so maybe it would be worth it to have a new major version?

**Comment by bytehead** [comment]
Yes.

**Comment by simoheinonen** [comment]
Anything I can do still? When do you think we could get this merged and new version tagged?

**Comment by bytehead** [comment]
Thanks for updating!

**Comment by simoheinonen** [comment]
2 weeks until dropbox api v1 shuts down

**Comment by bytehead** [comment]
I just think about to put this in a minor release, because we do not break BC, it's actually Dropbox who stops the service (and the V1 adapter gets useless anyway). The bundle itself is still PHP5 compatible until you use `spatie/flysystem-dropbox`. 
What do you think?

**Comment by bytehead** [comment]
Link to the announcement: https://blogs.dropbox.com/developers/2016/06/api-v1-deprecated/

**Comment by simoheinonen** [comment]
Sounds good to me but we need to do something about the tests. They fail because the dropbox adapter require php7

**Comment by bytehead** [comment]
Maybe we don't require `spatie/flysystem-dropbox` in `require-dev` then?

**Comment by simoheinonen** [comment]
Tested this in production and seems to be working!

**Comment by simoheinonen** [comment]
Do you think we can get this out this week?

**Comment by bytehead** [comment]
Thanks! Yes, it should be possible.

**Comment by flebourg** [comment]
I try to replace league/flysystem-dropbox with [https://github.com/srmklive/flysystem-dropbox-v2](url) locally and it's seems to work (with php5.6)

So no need to use spatie/flysystem-dropbox how only work with php7

**Pull request merged**
