### PR TITLE
Add support for custom adapter

### PR DESCRIPTION
**Pull request by yellow1912**
Please note that no test has been added yet.

### CODE REVIEW

**Comment by yellow1912** [comment]
Also add support for the new phpredis cache adapter :). I have another commit coming for supporting Azure storage so it's best that this pull request is merged before that to prevent one pull request from having too many changes

**Comment by bytehead** [comment]
I can't update my dependencies with this PR pulled in:

```bash
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - league/flysystem-azure 1.0.2 requires pear-pear.php.net/mail_mime * -> no matching package found.
    - league/flysystem-azure 1.0.1 requires pear-pear.php.net/mail_mime * -> no matching package found.
    - league/flysystem-azure 1.0.0 requires pear-pear.php.net/mail_mime * -> no matching package found.
    - Installation request for league/flysystem-azure ~1.0 -> satisfiable by league/flysystem-azure[1.0.0, 1.0.1, 1.0.2].
Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.
```

Can you fix this?

**Comment by bytehead** [comment]
I pushed your changes into a new branch [feature-custom-adapters](https://github.com/1up-lab/OneupFlysystemBundle/tree/feature-custom-adapters). This changes need to be tested.

**Comment by yellow1912** [comment]
Unfortunately there is not much I can do since MS Azure has not updated their packages to reflect the new changes with pear packages yet.

For now, on my own composer I override their code with

{ "type": "vcs", "url": "https://github.com/Nilead/flysystem-azure" },
{ "type": "vcs", "url": "https://github.com/Nilead/azure-sdk-for-php" }

Hopefully they will fix this situation soon enough.

Another way to get around it is to use:

"repositories": [
    {
        "type": "pear",
        "url": "http://pear.php.net"
    }
],

**Comment by bytehead** [comment]
I've added a hint here: https://github.com/1up-lab/OneupFlysystemBundle/commit/b8571cdf20374466324160be8313e1b76a9111cc#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R40

**Comment by tobiassjosten** [comment]
@bytehead @yellow1912 What's the status of this? I'm needing the functionality and would love to give a hand if I can help move it forward.

**Comment by bytehead** [comment]
@tobiassjosten [here](https://github.com/1up-lab/OneupFlysystemBundle/tree/feature-custom-adapters) is the feature branch, which contains this custom adapter stuff. I didn't have any time so far to test it.

**Comment by tobiassjosten** [comment]
Thanks, @bytehead. I had a look but found an easier way to achieve what I wanted.

**Comment by bytehead** [comment]
No worries. You can easily provide a PR with your way/ideas.

**Comment by sheeep** [comment]
There is already [section in the documentation](https://github.com/1up-lab/OneupFlysystemBundle/blob/master/Resources/doc/adapter_custom.md) for own adapters. I think its best to let a user just add its own services, instead of adding this as a feature. What do you think? Will reopen if there is an advantage of this approach over simple service definitions.

**Pull request closed without merging**
