### PR TITLE
Test against PHP 7.4 (see #201)

### PR DESCRIPTION
**Pull request by mihaileu**

### CODE REVIEW

**Comment by mihaileu** [comment]
I think we can retry the build when https://github.com/php-build/php-build/pull/599 will be merged

**Comment by mihaileu** [comment]
@bytehead could you please retry the build, thanks

**Comment by bytehead** [comment]
Just started.

**Comment by bytehead** [comment]
Can you rebase this PR onto master?

**Comment by bytehead** [comment]
Thank you!

**Pull request merged**
