### PR TITLE
Add Azure Blob Storage adaptor factory

### PR DESCRIPTION
**Pull request by fredericbarthelet**
Add native support for Azure Blob Storage adapter.

### CODE REVIEW

**Comment by fredericbarthelet** [comment]
Hi @bytehead, happy to help :)
What I found out at the moment concerning the failling test :
- Test suit works normally on my local environnement (PHP 7.2.21)
- Test suit fails on master (I ran a quick test modifying only a documentation file from master and found out the error is the same on Travis)
- It appears method `$filesystem->getVisibility(filePath)` is returning file permission code `664` instead of expected `AdapterInterface::VISIBILITY_PUBLIC` constant

I would guess this has something to do with either Travis filesystem configuration or either bundle test env specific configuration. Do you have any input on the matter :) ?

**Comment by fredericbarthelet** [comment]
Hello @bytehead, did you had time to look at the PR :) ? Thanks

**Comment by bytehead** [comment]
Hey @fredericbarthelet 

I have looked at and into it and to be honest - I have no clue why travis returns a different value than any local environment. 

Failing tests are here: https://travis-ci.org/1up-lab/OneupFlysystemBundle/jobs/604543215
`League\Flysystem\Filesystem::getVisibility($path)` returns `public` on my local machines (and the one from @fredericbarthelet) but does return `0644` on travis.org.
@frankdejonge do you have any hint on this case?

**Comment by bytehead** [comment]
I've merged it in 9777444de3de22414c6125421cf1748037364fe2 and marked the failing tests as skipped. 
Thank you for your contribution! 🎉

**Comment by bytehead** [comment]
`3.2.0` is released :)

**Comment by navneetbhardwaj** [comment]
Why this is removed from the current version 4.2.2?

**Comment by bytehead** [comment]
It was at the time of the 4.0 release not Flysystem 2 compatible (removed along others in #217).

**Comment by frankdejonge** [comment]
@bytehead just got a notification around this and saw you asked a question. A little too late, but an aspect could be the `umask` setting that may be different on travis installation, I'm not sure since I moved everything away from Travis CI to GH Actions.

**Comment by bytehead** [comment]
@frankdejonge thank you for your response! In the meantime we're on GH Actions as well 👍

**Comment by bytehead** [comment]
@navneetbhardwaj I just saw, that the [Azure Blob Storate Adapter](https://flysystem.thephpleague.com/docs/adapter/azure-blob-storage/) is available in a newer version. I'll add this adapter as soon as possible.

**Comment by bytehead** [comment]
The Azure Blob Storage adapter was reintroduced in [4.5.0](https://github.com/1up-lab/OneupFlysystemBundle/releases/tag/4.5.0).

**Pull request closed without merging**
