### PR TITLE
Remove cache property from documentation

### PR DESCRIPTION
**Pull request by simoheinonen**

### CODE REVIEW

**Comment by bytehead** [comment]
Why?

**Comment by simoheinonen** [comment]
Why what?

**Comment by bytehead** [comment]
Why is there no cache anymore?

**Comment by simoheinonen** [comment]
As far as I understand it was removed in 4.0 but this documentation wasn't changed

**Comment by simoheinonen** [comment]
Wish there was cache feature again though :(

**Comment by bytehead** [comment]
The cache feature was actually removed in the underlaying flysystem library: https://flysystem.thephpleague.com/docs/upgrade-from-1.x/#miscellaneous-changes _The cached adapter was not ported to V2._

**Comment by simoheinonen** [comment]
Yeah, there's https://github.com/Lustmored/flysystem-v2-simple-cache-adapter but not sure if that one would be mature enough to add to this bundle?

**Review by bytehead — APPROVED** [review]

**Pull request merged**
