### PR TITLE
Update league/flysystem-* packages to ^2.0

### PR DESCRIPTION
**Pull request by bytehead**
- [x] .env support (#207 / #156) --> see #228

### CODE REVIEW

**Comment by fd6130** [comment]
Any chances this will be merge and release?

**Comment by bytehead** [comment]
@fd6130 I cannot see that your issue is related to this bundle. Check your requirement of the `league/flysystem`. 

Back to your question: It's on the list to finish this PR asap, but I didn't have time so far to complete it. You're welcome to test the branch `4.x` :)

**Comment by fullbl** [comment]
@bytehead is there something I can do to help with this PR?

**Comment by bytehead** [comment]
@fullbl I've would like to have .env support built in for release 4.0 (see tickets mentioned above) but I don't found time so far to work on that. Contributions are welcome :)

**Pull request merged**
