### PR TITLE
Allow the installation on PHP 8

### PR DESCRIPTION
**Pull request by derrabus**
Hello! 👋🏻 

I'd like to use your awesome bundle on PHP 8, so I'd like to ask if we could allow composer to install it.

### CODE REVIEW

**Comment by bytehead** [comment]
Hey Alexander

Yes, for sure!

**Comment by bytehead** [comment]
Don't know if tests will run through, but let's see :)

**Comment by derrabus** [comment]
The tests pass, but with deprecation warnings because of the deprecated `expectedException` annotations.

Bildschirmfoto 2020-12-07 um 11 50 13

**Comment by bytehead** [comment]
Is it intended to run on Symfony 3.4 with PHP 8? Will Symfony 3.4 support PHP 8?
https://travis-ci.org/github/1up-lab/OneupFlysystemBundle/jobs/748102802

**Comment by derrabus** [comment]
We have patched Symfony 3.4 for PHP 8.0, yes. But because the maintenance of the 3.4 branch has ended, I would consider the PHP 8 support as experimental. `KernelTestCase` of the 3.4 branch will probably only work if we use PHPUnit bridge to patch PHPUnit's return type declarations.

I can do that for you, but it's maybe enough to just skip that combination.

**Comment by bytehead** [comment]
I'll skip it :-)

**Pull request merged**
