### PR TITLE
Error on configuration #149

### PR DESCRIPTION
**Pull request by bedrandogan**

### CODE REVIEW

**Comment by jverdeyen** [comment]
Any updates on this review? @sheeep @bytehead  Thanks!

**Comment by bytehead** [comment]
Sorry for the delay & thanks for the fix!

**Comment by emodric** [comment]
@bytehead Is there a chance this could be migrated to 1.x ?

**Comment by bytehead** [comment]
Is an update to 2.x not possible for you? Only BC break is Dropbox Api V1 and no longer support for PHP5.

**Comment by emodric** [comment]
@bytehead Yep, I've realized that and opened the issue in the repo requiring the bundle: https://github.com/ezsystems/ezpublish-kernel/pull/2110

**Comment by bytehead** [comment]
Nice. Let me know, otherwise we can possibly backport this changes.

**Comment by emodric** [comment]
@bytehead eZ kernel allowed version 2 of the bundle in https://github.com/ezsystems/ezpublish-kernel/pull/2110, so no need to backport as far as I'm concerned ;)

**Comment by bytehead** [comment]
Thank you for clarification!

**Pull request merged**
