### PR TITLE
Fix spelling of "defaultVisiblity" => "defaultVisibility"

### PR DESCRIPTION
**Pull request by Chris53897**
https://github.com/1up-lab/OneupFlysystemBundle/issues/255

I just come across this, as my IDE did notice.

Needs a closer look.

### CODE REVIEW

**Comment by bytehead** [comment]
I consider this as a bug - probably didn't work properly. Only if you misspelled it as well in your config. What do you think?

**Comment by Chris53897** [comment]
In my eyes it is a bug fix and a BC Break. I guess People find out quickly after upgrading.Composer will clear cache and give a warning/error about wrong config.I think this can be part of a minor update, but with a good visible info, about this change.Am 11.03.2024 um 10:30 schrieb David Greminger ***@***.***>:﻿
I consider this as a bug - probably didn't work properly. Only if you misspelled it as well in your config. What do you think?

**Comment by bytehead** [comment]
I call it clearly a bug and it will be fixed in a bugfix release 👍

**Review by bytehead — APPROVED** [review]

**Comment by bytehead** [comment]
Thank you ❤️

**Pull request merged**
