### PR TITLE
Add Google Cloud Storage support.

### LINKED ISSUE #106: Support the Google Cloud Storage Adapter
https://github.com/Superbalist/flysystem-google-storage

### PR DESCRIPTION
**Pull request by tmirks**
Resolves #106.

### CODE REVIEW

**Comment by bytehead** [comment]
Thank you! I'll check it asap.

**Comment by tmirks** [comment]
@bytehead Are you concerned that PHP 5.4 tests aren't passing? Should we remove PHP 5.4 from Travis tests?

**Comment by tmirks** [comment]
@bytehead Oops ignore last comment, I realize you already did!

**Comment by bytehead** [comment]
All good 👌  - Thank you!

**Pull request merged**
