### PR TITLE
Add google cloud storage adapter

### PR DESCRIPTION
**Pull request by bytehead**
See #237

### CODE REVIEW

**Comment by Kenariosz** [comment]
Hey!

Do you have any idea when this feature will be released?

**Comment by johnhout** [comment]
@bytehead bump

**Comment by bytehead** [comment]
Could you test the feature branch?

**Comment by bytehead** [comment]
I think there is still some error (see #237), I haven't found time so far to fix.

**Comment by bytehead** [comment]
[4.1.0](https://github.com/1up-lab/OneupFlysystemBundle/releases/tag/4.1.0) is released. Sorry for the waiting time.

**Pull request merged**
