### PR TITLE
Add support for defining filesystem plugins in config

### PR DESCRIPTION
**Pull request by yellow1912**
It makes sense to define the list plugins we want to use for the
filesystem directly in the config. This way we don't have to mess
with the service's definition.

### CODE REVIEW

**Comment by yellow1912** [comment]
I will add this to the docs if the PR is accepted :)

**Comment by yellow1912** [comment]
@sheeep any thought on this?

**Comment by sheeep** [comment]
This is a great idea! Should we get rid of the configuration way of defining plugins (`oneup_flysystem.plugin` tag)? What do you think? Focus on a single method, or let both possibilities in this bundle?

We should probably add [the plugins provided by Flysystem itself](https://github.com/thephpleague/flysystem/tree/master/src/Plugin) as services.

**Comment by yellow1912** [comment]
If you are not worried about Backward Compatibility I say we provide only 1 single method to make things simple

**Comment by sheeep** [comment]
As we're bumping the major version anyway, I'd suggest to stick to a single method.

**Comment by yellow1912** [comment]
What is the next step? Do you want something else to be added/removed before we go ahead with this PR? :)

**Comment by sheeep** [comment]
Take a look at your repository. I created a pull request which removes the old method of attaching plugins and defines the ones that are already provided by the flysystem library.

Another thing to discuss. Removing the `PluginPass` also removes the support for attaching a plugin "globally" which means: to every defined filesystem. Should we re-add this feature?

I've thought about something like:

```yml
oneup_flysystem:
    plugins:
        - global_plugin
    filesystems:
        my_filesystem:
            plugins:
                - local_plugin
```

Whereas `global_plugin` is available for every configured filesystem and `local_plugin` only for `my_filesystem`.

What do you think?

**Comment by yellow1912** [comment]
Definitely makes sense to me :)

**Comment by sheeep** [comment]
> Definitely makes sense to me :)
Very well. I'll create another pull request to your repository asap. :)

**Pull request merged**
